version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - export LC_ALL="en_US.utf8"
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - cp appspec.yml target/
artifacts:
  files:
    - target/*
  discard-paths: yes

